model:
  name: simple

eksctl:
  name: new-main-cluster
  version: "1.30"
  region: us-west-2
  nodegroup-name: linux-nodes
  node-type: t3.medium
  nodes: "1"

training:
  batch_size: 32
  lr: 0.001
  epochs: 8
  accumulation_steps: 4
  device: cpu  # cpu or cuda
  
training-setup:
  image: "arthurstupa/cifar10-detector:latest"
  num_workers: 2
  num_gpus: 0 # amount of gpus to use per pod
  script: "src/train.py"

wandb:
  use: true
  project: mnist
  log_interval: 10

ddp:
  backend: gloo  # gloo for CPU, nccl for GPU
  port: 29000
