apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: mpi
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: arthurstupa/mnist-detector:latest
              name: mnist-launcher
              env:
              - name: DATA_PATH
                value: /app/data
              command:
              - bash
              - -c
              - |
                export MASTER_ADDR=$(awk 'NR==1{print $1}' /etc/mpi/hostfile)

                echo "Launcher using MASTER_ADDR=$MASTER_ADDR"

                mpirun --allow-run-as-root \
                  --tag-output \
                  -mca plm_rsh_args "-o StrictHostKeyChecking=no" \
                  -x MASTER_ADDR \
                  -x DATA_PATH \
                  python train.py
              ports:
                - containerPort: 22
              volumeMounts:
              - name: dataset
                mountPath: /app/data
          volumes:
          - name: dataset
            persistentVolumeClaim:
              claimName: mnist-pvc

    Worker:
      replicas: 2
      template:
        spec:
          containers:
            - image: arthurstupa/mnist-detector:latest
              name: mnist-worker
              ports:
                - containerPort: 22
              volumeMounts:
              - name: dataset
                mountPath: /app/data
          volumes:
          - name: dataset
            persistentVolumeClaim:
              claimName: mnist-pvc
