global:
  scrape_interval: 15s
  evaluation_interval: 15s

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'ml_training'
        static_configs:
          - targets: ['ml-training-metrics.default.svc.cluster.local:8001']
