model:
  name: simple

training:
  batch_size: 32
  lr: 0.001
  epochs: 2
  device: cpu  # or cuda
  
training_setup:
  image: "arthurstupa/cifar10-detector:latest"
  num_workers: 4
  script: "train.py"

wandb:
  use: true
  project: mnist
  log_interval: 10

ddp:
  backend: gloo  # or nccl for GPU
  port: 29500
