model:
  name: simple

training:
  batch_size: 32
  lr: 0.001
  epochs: 2
  device: cpu  # or cuda

wandb:
  use: true
  project: mnist
  log_interval: 10

ddp:
  backend: gloo  # or nccl for GPU
  port: 29500
