apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-training-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ml-training-metrics
  endpoints:
    - port: metrics
      interval: 15s
