apiVersion: v1
kind: Service
metadata:
  name: ml-training-service
  labels:
    app: ml-training-metrics
spec:
  selector:
    app: ml-training-metrics
  ports:
    - name: metrics
      port: 80
      targetPort: 8001
