model:
  name: simple

training:
  batch_size: 32
  lr: 0.001
  epochs: 8
  accumulation_steps: 4
  device: cpu  # cpu or cuda
  
training_setup:
  image: "arthurstupa/cifar10-detector:latest"
  num_workers: 8
  num_gpus: 0 # amount of gpus to use per pod
  script: "src/train.py"

wandb:
  use: true
  project: mnist
  log_interval: 10

ddp:
  backend: gloo  # gloo for CPU, nccl for GPU
  port: 29000
