name: Test, Build, and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image (for testing only)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Dockerfile
        load: true
        tags: |
          local/cifar10-detector:latest
          arthurstupa/cifar10-detector:v2
          arthurstupa/cifar10-detector:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run unit tests inside container
      run: |
        docker run --rm local/cifar10-detector:latest pytest tests/

    - name: Push image (only if tests pass)
      run: |
        docker push arthurstupa/cifar10-detector:v2
        docker push arthurstupa/cifar10-detector:latest
